const assert = require('node:assert/strict');
const { loadGame } = require('./game-harness');
const { DS } = loadGame();
DS.PlayerIdentity.set({type:'scripted', policy:'bug-report-suite', policyVersion:'1'});
DS.Meta.newGame();
DS.State.newRun();
DS.State.run.floor = 0;
DS.Combat.initCombat([{name:'Report Dummy', maxHp:20, intents:[{type:'attack', dmg:2, targeting:'front'}]}]);
DS.State.combat.hand = [{baseId:'fighter_strike', id:'strike-1', name:'Strike', heroCls:'fighter', cost:1, type:'attack'}];
const report = DS.BugReport.capture('The damage preview looked wrong.');
assert.equal(report.type, 'darkspire-bug-report');
assert.equal(report.game, 'Darkspire');
assert.equal(report.note, 'The damage preview looked wrong.');
assert.ok(report.version);
assert.equal(report.run.floor, DS.State.run.floor);
assert.equal(report.cards.hand[0].id, 'fighter_strike');
assert.equal(report.fight.enemies[0].name, 'Report Dummy');
assert.ok(Array.isArray(report.recentActions));
const serialized = JSON.stringify(report);
assert.equal(serialized.includes('bug-report-suite'), false, 'player identity must stay out of reports');
assert.equal(serialized.includes('darkspire_journal_v1'), false, 'storage keys must stay out of reports');
assert.equal(serialized.includes('campaign'), false, 'campaign metadata must stay out of reports');
console.log('PASS bug-report: captures version, fight state, cards, recent actions and player note');
