const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),noop=()=>{},memory=new Map();
const ctx={console,setTimeout:()=>0,clearTimeout:noop,requestAnimationFrame:()=>0,cancelAnimationFrame:noop,addEventListener:noop,document:{body:{appendChild:noop,addEventListener:noop},head:{appendChild:noop},getElementById:()=>null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:noop,createElement:()=>({setAttribute:noop,appendChild:noop,remove:noop,style:{},classList:{add:noop,remove:noop}})},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)}};ctx.window=ctx;vm.createContext(ctx);
for(const m of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script src="([^"]+)"/g)) vm.runInContext(fs.readFileSync(path.join(root,m[1]),'utf8'),ctx,{filename:m[1]});
const {DS}=ctx,C=DS.Combat;DS.UI.render=noop;C.sleep=async()=>{};DS.PlayerIdentity.set({type:'scripted',policy:'regression-suite',policyVersion:'1'}); DS.Meta.newGame();
function setup() { DS.State.newRun(); C.initCombat([{name:'Front',maxHp:150,intents:[{type:'attack',dmg:8,targeting:'random'}]},{name:'Rear',maxHp:150,intents:[{type:'attack',dmg:8,targeting:'front'}]},{name:'Support',maxHp:150,intents:[{type:'defend',block:3}]}]); C.COMBOS.forEach(x=>x._triggered=false); return DS.State.combat; }
function card(id,owner=0) { const def=Object.values(DS.Cards).filter(Array.isArray).flat().find(c=>c.id===id); assert.ok(def,id); return Object.assign({},def,{baseId:id,id:id+'_test',heroIdx:owner,heroCls:id.split('_')[0]}); }
function play(c,t) { const b=DS.State.combat;b.hand=[c];b.energy=10;C.playCard(0,t); }
(async()=>{
let b=setup(),h=DS.State.run.heroes,e=b.enemies;
const strike=card('fighter_strike');assert.equal(C.validTarget(strike,e[2]),false);let hp=e[2].hp;play(strike,e[2]);assert.equal(e[2].hp,hp);assert.equal(b.energy,10,'illegal target consumes nothing');
let original=C.intentTarget(e[0],0);h[0].pos=4;h[3].pos=1;assert.equal(C.intentTarget(e[0],0),original,'victim committed despite hero movement');
play(card('fighter_hook'),e[2]);assert.equal(e[2].pos,1);e[2].hp=1;C.dealDamage(e[2],3);assert.deepEqual(Array.from(C.aliveEnemies(),x=>x.pos).sort(),[1,2]);
b=setup();h=DS.State.run.heroes;e=b.enemies;play(card('fighter_intercept'),h[1]);assert.equal(h[1].guard,h[0].id);h[0].riposte=2;h[0].riposteDamage=5;e[0].currentIntent={type:'attack_multi',dmg:8,hits:3};e[0].intentTargets=[h[1].id,h[1].id,h[1].id];e[1].stunned=true;e[2].stunned=true;
let f=C.forecastIncoming();assert.equal(f[h[0].id].damage,17);assert.equal(f[h[1].id].damage,0);hp=h[0].hp;let enemyHp=e[0].hp;await C.endTurn();assert.equal(h[0].hp,hp-17);assert.equal(e[0].hp,enemyHp-10);assert.equal(h[1].guard,null);
b=setup();h=DS.State.run.heroes;e=b.enemies;e[0].hp=4;e[0].currentIntent={type:'attack_multi',dmg:2,hits:3};e[0].intentTargets=[h[0].id,h[0].id,h[0].id];e[1].stunned=true;e[2].stunned=true;h[0].riposte=2;h[0].riposteDamage=5;hp=h[0].hp;await C.endTurn();assert.equal(h[0].hp,hp-2,'dead attacker loses remaining hits');
b=setup();e=b.enemies;e[0]._marked=true;e[0]._markBonus=4;hp=e[0].hp;C.dealDamage(e[0],5);C.dealDamage(e[0],5);assert.equal(e[0].hp,hp-14,'mark adds exactly once');e[0].block=20;play(card('fighter_sunder'),e[0]);assert.equal(e[0].block,0);assert.equal(e[0].hp,hp-15);
b=setup();h=DS.State.run.heroes;e=b.enemies;const retained=card('rogue_reserve_blade',1);b.hand=[retained];e.forEach(x=>x.stunned=true);await C.endTurn();assert.ok(b.hand.includes(retained));b.hand=Array.from({length:10},()=>card('fighter_strike'));let draws=b.drawPile.length;C.drawCard();assert.equal(b.drawPile.length,draws,'full hand does not burn cards');
b=setup();play(card('necromancer_ash_covenant'));assert.equal(DS.State.run.heroes[0].block,3,'payoff triggers own exhaustion');const shard=C.generateCard('tactical_shard',0);b.enemies.forEach(x=>x.stunned=true);await C.endTurn();assert.ok(b.exhaustPile.includes(shard));assert.equal(DS.State.run.heroes[0].block,0,'player Block expires at the next player turn');
b=setup();const spare=card('fighter_strike'),improvise=card('rogue_improvise',1);b.hand=[spare,improvise];b.energy=3;C.playCard(1,null);assert.ok(b.exhaustPile.includes(improvise));assert.ok(!b.hand.includes(improvise),'discard index shift does not leave played card');
b=setup();const finisher=card('wizard_arcane_barrage',3);b.hand=[finisher];b.energy=3;hp=b.enemies[0].hp;C.playCard(0,b.enemies[0]);assert.equal(b.energy,0);assert.equal(b.enemies[0].hp,hp-18);assert.equal(finisher.value,6);
b=setup();const backstab=card('rogue_backstab',1);b.hand=[backstab];b.energy=1;assert.equal(C.cardReach(backstab).join(','),'1,2');assert.equal(C.validTarget(backstab,b.enemies[0]),true,'Backstab reaches enemy rank 1');assert.equal(C.validTarget(backstab,b.enemies[1]),true,'Backstab reaches enemy rank 2');assert.equal(C.validTarget(backstab,b.enemies[2]),false,'Backstab cannot reach enemy rank 3');hp=b.enemies[0].hp;C.playCard(0,b.enemies[0]);assert.equal(b.enemies[0].hp,hp-11,'Backstab deals its high single-target damage');
b=setup();const backstep=card('rogue_evade',1);b.hand=[backstep];b.energy=1;assert.equal(C.canPlayCard(backstep).playable,true);const rogue=DS.State.run.heroes[1];const oldPos=rogue.pos;C.playCard(0,null);assert.equal(rogue.pos,oldPos+1,'Backstep moves the rogue backward after blocking');
b=setup();const defendingEnemy=b.enemies[2];assert.equal(defendingEnemy.block,3,'Enemy defend block applies when intent is rolled');C.pickIntent(defendingEnemy);assert.equal(defendingEnemy.block,3,'Rerolling defend replaces Block instead of stacking');defendingEnemy.intentPool=[{type:'attack',dmg:1,targeting:'front'}];await C.endTurn();assert.equal(defendingEnemy.block,3,'Enemy defend block persists into the player turn');hp=defendingEnemy.hp;const missile=card('wizard_magic_missile',3);b.hand=[missile];b.energy=1;C.playCard(0,defendingEnemy);assert.equal(defendingEnemy.block,0,'Enemy block is consumed by player damage');assert.equal(defendingEnemy.hp,hp-3,'Remaining damage passes through enemy block');
b=setup();const free=card('fighter_strike');free._turnCost=0;b.discardPile.push(free);b.enemies.forEach(x=>x.stunned=true);await C.endTurn();assert.equal(free._turnCost,undefined,'cost expires even outside hand');
b=setup();const wound=C.generateCard('tactical_wound',0);assert.equal(C.canPlayCard(wound).playable,false);assert.equal(DS.State.run.deck.some(x=>x.baseId==='tactical_wound'),false,'temporary cards never pollute expedition deck');
b=setup();DS.State.run.deck=Array.from({length:6},()=>card('rogue_escape_plan',1)).concat(Array.from({length:10},()=>card('fighter_strike')));C.initCombat(DS.Enemies.normal[0]);assert.equal(DS.State.combat.hand.length,6);assert.ok(DS.State.combat.hand.every(c=>c.innate),'all six innate cards drawn without exceeding cap');
b=setup();b.enemies[0].currentIntent={type:'attack',dmg:1,targeting:'front',push:2,statusCard:'tactical_wound'};b.enemies[0].intentTargets=[DS.State.run.heroes[0].id];b.enemies[1].stunned=true;b.enemies[2].stunned=true;await C.endTurn();assert.equal(DS.State.run.heroes[0].pos,3,'telegraphed attack breaks formation');assert.ok(b.discardPile.concat(b.drawPile,b.hand).some(c=>c.baseId==='tactical_wound'),'enemy adds real status card');
b=setup();const rewardCard=card('rogue_reserve_blade',1),oldPool=DS.Cards.getRewardPool;
DS.Cards.getRewardPool=()=>[rewardCard];const rewardEl={classList:{add:noop},appendChild:noop},skipEl={},rootEl={appendChild:noop,querySelector:()=>rewardEl,querySelectorAll:()=>[]};
const getEl=ctx.document.getElementById;ctx.document.getElementById=id=>id==='btn-skip-reward'?skipEl:null;
DS.UI.renderReward(rootEl);const before=DS.State.run.deck.length;rewardEl.onclick();rewardEl.onclick();
const acquired=DS.State.run.deck[DS.State.run.deck.length-1];assert.equal(acquired.retain,true,'reward click preserves retain');assert.ok(Array.isArray(acquired.prefPos),'reward preserves launch ranks');assert.equal(DS.State.run.deck.length,before+1,'double click cannot duplicate reward');DS.Cards.getRewardPool=oldPool;ctx.document.getElementById=getEl;
b=setup();const fighterOnly=DS.Cards.getRewardPool(3,['fighter']);assert.ok(fighterOnly.length>0);assert.ok(fighterOnly.every(c=>c.heroCls==='fighter'),'card rewards stay inside the active class pool');
b=setup();const barrage=card('wizard_arcane_barrage',3);b.hand=[barrage];b.energy=3;hp=b.enemies[0].hp;C.playCard(0,b.enemies[0]);assert.equal(b.enemies[0].hp,hp-18,'Arcane Barrage spends all available energy');
b=setup();const strengthCard=card('fighter_strike');DS.State.run.heroes[0].strength=2;DS.State.run.heroes[0].power=1;b.enemies[0].block=5;b.enemies[0].vulnerable=1;const breakdown=C.cardDamageBreakdown(strengthCard,b.enemies[0]);assert.deepEqual({base:breakdown.base,strength:breakdown.strength,power:breakdown.power,incoming:breakdown.incoming,blockAbsorbed:breakdown.blockAbsorbed,hpLoss:breakdown.hpLoss},{base:7,strength:2,power:1,incoming:15,blockAbsorbed:5,hpLoss:10});assert.equal(C.cardFlatDamage(strengthCard),10);assert.equal(C.cardDamage(strengthCard,b.enemies[0]),15,'preview includes Strength, power and Vulnerable');b.hand=[strengthCard];b.energy=1;hp=b.enemies[0].hp;C.playCard(0,b.enemies[0]);assert.equal(b.enemies[0].hp,hp-10,'played damage matches preview Block/HP loss');
b=setup();DS.State.run.floor=6;C.initCombat([{name:'Scaled Check',maxHp:20,intents:[{type:'attack',dmg:9,targeting:'front'}]}]);assert.equal(DS.State.combat.enemies[0].intentPool[0].dmg,9,'enemy damage is not secretly floor-scaled');
b=setup();C.initCombat(DS.Enemies.boss[3]);const lord=DS.State.combat.enemies[0];assert.equal(lord.currentIntent.type,'attack_lifesteal','Vampire Lord opens with lifesteal pressure');DS.State.combat.enemies[1].hp=0;C.pickIntent(lord);assert.equal(lord.currentIntent.type,'summon','Vampire Lord prioritizes restoring dead bats');
b=setup();DS.State.screen='combat';DS.State._runRosterMap={0:3,1:7};DS.State.selectedHeroes=[3,7];DS.State.run._customLedger={paid:17};
const savedShard=C.generateCard('tactical_shard',0);savedShard._turnCost=0;savedShard._combatCost=1;DS.State.run.heroes[1].guard=DS.State.run.heroes[0].id;DS.State.run.heroes[0].riposte=2;
C.COMBOS[0]._triggered=true;const snapshot=JSON.stringify({hand:b.hand.map(c=>c.id),targets:b.enemies.map(e=>e.intentTargets),rng:DS.State.run._combatRng});DS.State.save();const nextRandom=C.random();
DS.State.run=null;DS.State.combat=null;assert.ok(DS.State.load(),'real combat save restores');b=DS.State.combat;assert.equal(JSON.stringify({hand:b.hand.map(c=>c.id),targets:b.enemies.map(e=>e.intentTargets),rng:DS.State.run._combatRng}),snapshot);assert.equal(C.random(),nextRandom,'future combat randomness is not rerolled');
const loadedShard=b.hand.find(c=>c.id===savedShard.id);assert.equal(typeof loadedShard.effect,'function');assert.equal(loadedShard.ethereal,true);assert.equal(loadedShard.temporary,true);assert.equal(loadedShard._turnCost,0);assert.equal(loadedShard._combatCost,1);assert.equal(DS.State.run.heroes[1].guard,DS.State.run.heroes[0].id);assert.equal(DS.State.run._customLedger.paid,17);assert.equal(DS.State._runRosterMap[1],7);assert.ok(C.COMBOS[0]._triggered);
const savedRaw=memory.get('darkspire_save');b.animating=true;DS.State.save();assert.equal(memory.get('darkspire_save'),savedRaw,'animation cannot overwrite durable checkpoint');b.animating=false;b.enemies.forEach(e=>e.stunned=true);await C.endTurn();assert.ok(b.exhaustPile.some(c=>c.id===savedShard.id),'loaded ethereal card expires correctly');
b=setup();DS.State.screen='combat';DS.State.save();const decisionSave=memory.get('darkspire_save');await C.endTurn();const resumedResult=JSON.stringify({hp:DS.State.run.heroes.map(h=>h.hp),intents:DS.State.combat.enemies.map(e=>[e.currentIntent,e.intentTargets]),hand:DS.State.combat.hand.map(c=>c.id),rng:DS.State.run._combatRng});memory.set('darkspire_save',decisionSave);assert.ok(DS.State.load());await C.endTurn();assert.equal(JSON.stringify({hp:DS.State.run.heroes.map(h=>h.hp),intents:DS.State.combat.enemies.map(e=>[e.currentIntent,e.intentTargets]),hand:DS.State.combat.hand.map(c=>c.id),rng:DS.State.run._combatRng}),resumedResult,'resumed enemy round matches uninterrupted round exactly');
console.log('PASS combat-depth: reach, target commitment, displacement/collapse, guard forecasts, bounded riposte, mark, armor break, retain/hand cap, exhaust/ethereal, deliberate discard, X costs, cost reset, generated status boundaries');
})().catch(e=>{console.error(e);process.exitCode=1;});
