const assert = require('node:assert/strict');
const {loadGame} = require('./game-harness');
const {DS,memory,sandbox} = loadGame();
DS.UI.render = ()=>{};
DS.PlayerIdentity.set({type:'scripted',policy:'regression-suite',policyVersion:'1'}); DS.Meta.newGame();
DS.State.newRun();
const id = DS.State.run.journalId;
assert.ok(id);
DS.Combat.initCombat(DS.Enemies.pickEncounter('normal'));
const target = DS.State.combat.enemies[0];
DS.Combat.dealDamage(target,3);
DS.State.save();
let archive = DS.Telemetry.archive();
assert.ok(archive.events.some(e=>e.type==='run.start'));
const damage = archive.events.find(e=>e.type==='combat.dealDamage');
assert.ok(damage);
assert.equal(damage.detail.args[1],3);
assert.ok(damage.state.run.deck.length>0);
assert.ok(damage.state.combat.hand.every(c=>c.id && c.baseId));
assert.ok(damage.detail.before.combat.enemies[0].hp>=damage.state.combat.enemies[0].hp);
const reloaded = loadGame({memory}).DS;
reloaded.UI.render = ()=>{}; reloaded.PlayerIdentity.set({type:'scripted',policy:'reload-regression',policyVersion:'1'});
assert.equal(reloaded.State.load(),true);
assert.equal(reloaded.State.run.journalId,id);
archive = reloaded.Telemetry.archive();
assert.ok(archive.events.some(e=>e.type==='run.resume'));
assert.equal(new Set(archive.events.map(e=>e.seq)).size,archive.events.length);
const before = archive.events.length;
reloaded.Meta.newGame();
assert.equal(reloaded.Telemetry.archive().events.length,before,'new campaign must not erase history');
const set = sandbox.localStorage.setItem;
const error = sandbox.console.error;
sandbox.console = {...console,error:()=>{}};
sandbox.localStorage.setItem = ()=>{throw new Error('QuotaExceededError');};
DS.Telemetry.record('quota-test');
assert.equal(DS.Telemetry.archive().unsavedEvents,1);
assert.ok(DS.Telemetry.archive().events.some(e=>e.type==='quota-test'));
assert.match(DS.Telemetry.storageError,/Quota/);
sandbox.localStorage.setItem = set;
sandbox.console.error = error;
console.log('PASS: real-script telemetry initial state, semantic damage, full deck/hand snapshots, reload continuity, no campaign deletion, quota-safe export buffer');
