/** Reviewed runtime exports only. Keys are Phaser texture names. */
export const IMAGE_ASSETS = {
  dungeon: "renders/hollow-cathedral.png",
  camp: "renders/campfire-environment.png",
  town: "renders/hamlet-environment.png",
  rest: "renders/quiet-chapel.png",
  barbarian: "sprites/campfire-barbarian.png",
  ranger: "sprites/campfire-ranger.png",
  necromancer: "sprites/campfire-necromancer.png",
  paladin: "sprites/campfire-paladin.png",
  "barbarian-action": "sprites/campfire-barbarian.png",
  "ranger-action": "sprites/campfire-ranger.png",
  "necromancer-action": "sprites/campfire-necromancer.png",
  "paladin-action": "sprites/campfire-paladin.png",
  fighter: "sprites/campfire-fighter.png",
  rogue: "sprites/campfire-rogue.png",
  cleric: "sprites/campfire-cleric.png",
  wizard: "sprites/campfire-wizard.png",
  "fighter-action": "sprites/fighter-action.png",
  "rogue-action": "sprites/rogue-action.png",
  "cleric-action": "sprites/cleric-action.png",
  "wizard-action": "sprites/wizard-action.png",
  sentinel: "sprites/enemy-sentinel.png",
  occultist: "sprites/enemy-occultist.png",
  wraith: "sprites/enemy-wraith.png",
  beast: "sprites/enemy-beast.png",
  goblin: "sprites/enemy-goblin.png",
  bellkeeper: "sprites/bellkeeper.png",
} as const;
