import type { CardDef } from "./content";

/** The four returning disciplines. Rules use the same resolved effects as the original classes. */
export const EXTRA_CLASSES = {
  barbarian: {
    name: "Brynja",
    title: "Barbarian",
    hp: 58,
    color: "#cf9274",
    paths: ["Berserker", "Reaver", "Totemguard"],
  },
  ranger: {
    name: "Rowan",
    title: "Ranger",
    hp: 40,
    color: "#a1b87c",
    paths: ["Sharpshooter", "Trapper", "Warden of Thorns"],
  },
  necromancer: {
    name: "Morrow",
    title: "Necromancer",
    hp: 34,
    color: "#bb9bc9",
    paths: ["Reaper", "Plaguecaller", "Bonebinder"],
  },
  paladin: {
    name: "Ser Caelan",
    title: "Paladin",
    hp: 50,
    color: "#dac785",
    paths: ["Crusader", "Lightbearer", "Oathkeeper"],
  },
};
export const EXTRA_STARTERS = {
  barbarian: ["hew", "hew", "endure", "onslaught"],
  ranger: ["arrow", "arrow", "camouflage", "pinning-shot"],
  necromancer: ["grave-bolt", "grave-bolt", "bone-ward", "blight"],
  paladin: ["oath-strike", "oath-strike", "aegis-of-dawn", "lay-on-hands"],
};
const make = (
  owner: CardDef["owner"],
  id: string,
  name: string,
  effect: CardDef["effect"],
  cost: number,
  value: number,
  target: CardDef["target"],
  ranks: number[],
  reach: number[],
  text: string,
  extra: Partial<CardDef> = {},
): CardDef => ({
  owner,
  id,
  name,
  effect,
  cost,
  value,
  target,
  ranks,
  reach,
  text,
  flavor: "A lesson carried out of the dark.",
  exhaust: false,
  ...extra,
});
const all = [1, 2, 3, 4];
export const EXTRA_CARDS: CardDef[] = [
  make(
    "barbarian",
    "hew",
    "Hew",
    "strike",
    1,
    10,
    "enemy",
    [1, 2],
    [1, 2],
    "Deal {v} damage.",
  ),
  make(
    "barbarian",
    "endure",
    "Endure",
    "block",
    1,
    10,
    "self",
    [],
    [],
    "Gain {v} Block. Cleanse Poison.",
    { cleanse: true },
  ),
  make(
    "barbarian",
    "onslaught",
    "Onslaught",
    "strike",
    2,
    19,
    "enemy",
    [1, 2, 3],
    [1, 2],
    "Deal {v} damage. Advance one rank.",
    { move: -1 },
  ),
  make(
    "barbarian",
    "earthsplitter",
    "Earthsplitter",
    "cleave",
    2,
    10,
    "all",
    [1, 2],
    [],
    "Deal {v} damage to every enemy.",
  ),
  make(
    "barbarian",
    "war-howl",
    "War Howl",
    "block",
    1,
    6,
    "self",
    [],
    [],
    "Gain {v} Block. Draw 2 cards. Exhaust.",
    { draw: 2, exhaust: true },
  ),
  make(
    "barbarian",
    "crushing-blow",
    "Crushing Blow",
    "strike",
    2,
    16,
    "enemy",
    [1, 2],
    [1, 2],
    "Deal {v} damage. Reduce its next attack by 6.",
    { weaken: 6 },
  ),
  make(
    "barbarian",
    "iron-hide",
    "Iron Hide",
    "block",
    2,
    20,
    "self",
    [],
    [],
    "Gain {v} Block.",
  ),
  make(
    "barbarian",
    "wild-charge",
    "Wild Charge",
    "strike",
    1,
    11,
    "enemy",
    [2, 3, 4],
    [1, 2],
    "Deal {v} damage. Advance one rank. Gain 3 Block.",
    { move: -1, selfBlock: 3 },
  ),
  make(
    "barbarian",
    "last-stand",
    "Last Stand",
    "block",
    1,
    12,
    "self",
    [],
    [],
    "Gain {v} Block. Give every other ally 5 Block. Exhaust.",
    { partyBlock: 5, exhaust: true },
  ),
  make(
    "ranger",
    "arrow",
    "Hunting Arrow",
    "strike",
    1,
    9,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage.",
  ),
  make(
    "ranger",
    "camouflage",
    "Camouflage",
    "step",
    0,
    4,
    "self",
    [],
    [],
    "Gain {v} Block. Retreat one rank.",
  ),
  make(
    "ranger",
    "pinning-shot",
    "Pinning Shot",
    "strike",
    1,
    6,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage. Reduce its next attack by 3.",
    { weaken: 3 },
  ),
  make(
    "ranger",
    "volley",
    "Volley",
    "cleave",
    2,
    8,
    "all",
    [3, 4],
    [],
    "Deal {v} damage to every enemy.",
  ),
  make(
    "ranger",
    "serpent-arrow",
    "Serpent Arrow",
    "poison",
    1,
    4,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage. Apply 5 Poison.",
    { poisonAmount: 5 },
  ),
  make(
    "ranger",
    "hunters-focus",
    "Hunter's Focus",
    "block",
    0,
    3,
    "self",
    [],
    [],
    "Gain {v} Block. Draw 2 cards. Exhaust.",
    { draw: 2, exhaust: true },
  ),
  make(
    "ranger",
    "piercing-arrow",
    "Piercing Arrow",
    "strike",
    2,
    17,
    "enemy",
    [3, 4],
    [2, 3, 4],
    "Deal {v} damage, ignoring Block.",
    { pierce: true },
  ),
  make(
    "ranger",
    "snare",
    "Snare",
    "strike",
    1,
    4,
    "enemy",
    [],
    all,
    "Deal {v} damage. Reduce its next attack by 8. Exhaust.",
    { weaken: 8, exhaust: true },
  ),
  make(
    "ranger",
    "trail-ward",
    "Trail Ward",
    "block",
    1,
    8,
    "ally",
    [],
    [],
    "Give an ally {v} Block. Draw 1 card.",
    { draw: 1 },
  ),
  make(
    "necromancer",
    "grave-bolt",
    "Grave Bolt",
    "spell",
    1,
    9,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage.",
  ),
  make(
    "necromancer",
    "bone-ward",
    "Bone Ward",
    "block",
    1,
    8,
    "ally",
    [],
    [],
    "Give an ally {v} Block. Gain 3 Block.",
    { selfBlock: 3 },
  ),
  make(
    "necromancer",
    "blight",
    "Blight",
    "poison",
    1,
    3,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage. Apply 4 Poison.",
    { poisonAmount: 4 },
  ),
  make(
    "necromancer",
    "death-wave",
    "Death Wave",
    "cleave",
    2,
    9,
    "all",
    [3, 4],
    [],
    "Deal {v} damage to every enemy.",
  ),
  make(
    "necromancer",
    "enfeeble",
    "Enfeeble",
    "spell",
    1,
    5,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage. Reduce its next attack by 6.",
    { weaken: 6 },
  ),
  make(
    "necromancer",
    "ossuary",
    "Ossuary",
    "block",
    1,
    8,
    "self",
    [],
    [],
    "Gain {v} Block. Give every other ally 4 Block. Exhaust.",
    { partyBlock: 4, exhaust: true },
  ),
  make(
    "necromancer",
    "forbidden-rite",
    "Forbidden Rite",
    "block",
    0,
    2,
    "self",
    [2, 3, 4],
    [],
    "Gain {v} Block. Draw 2 cards. Exhaust.",
    { draw: 2, exhaust: true },
  ),
  make(
    "necromancer",
    "soul-rend",
    "Soul Rend",
    "spell",
    2,
    15,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage, ignoring Block. Gain 5 Block.",
    { pierce: true, selfBlock: 5 },
  ),
  make(
    "necromancer",
    "grave-bloom",
    "Grave Bloom",
    "poison",
    2,
    6,
    "enemy",
    [2, 3, 4],
    all,
    "Deal {v} damage. Apply 9 Poison. Exhaust.",
    { poisonAmount: 9, exhaust: true },
  ),
  make(
    "paladin",
    "oath-strike",
    "Oath Strike",
    "strike",
    1,
    8,
    "enemy",
    [1, 2],
    [1, 2],
    "Deal {v} damage. Gain 2 Block.",
    { selfBlock: 2 },
  ),
  make(
    "paladin",
    "aegis-of-dawn",
    "Aegis of Dawn",
    "block",
    1,
    9,
    "ally",
    [1, 2, 3],
    [],
    "Give an ally {v} Block.",
  ),
  make(
    "paladin",
    "lay-on-hands",
    "Lay on Hands",
    "heal",
    1,
    7,
    "ally",
    [1, 2, 3],
    [],
    "Restore {v} HP. Cleanse Poison. Exhaust.",
    { cleanse: true, exhaust: true },
  ),
  make(
    "paladin",
    "consecration",
    "cleave",
    "cleave",
    2,
    7,
    "all",
    [1, 2, 3],
    [],
    "Deal {v} damage to every enemy. Gain 5 Block.",
    { name: "Consecration", selfBlock: 5 },
  ),
  make(
    "paladin",
    "judicators-blade",
    "Judicator's Blade",
    "strike",
    2,
    17,
    "enemy",
    [1, 2],
    [1, 2, 3],
    "Deal {v} damage, ignoring Block.",
    { pierce: true },
  ),
  make(
    "paladin",
    "bastion",
    "Bastion",
    "block",
    2,
    12,
    "self",
    [],
    [],
    "Gain {v} Block. Give every other ally 7 Block.",
    { partyBlock: 7 },
  ),
  make(
    "paladin",
    "cleansing-light",
    "Cleansing Light",
    "heal",
    1,
    5,
    "ally",
    [],
    [],
    "Restore {v} HP. Cleanse Poison. Give 6 Block. Exhaust.",
    { cleanse: true, targetBlock: 6, exhaust: true },
  ),
  make(
    "paladin",
    "rebuke",
    "Rebuke",
    "spell",
    1,
    7,
    "enemy",
    [1, 2, 3],
    all,
    "Deal {v} damage. Reduce its next attack by 4.",
    { weaken: 4 },
  ),
  make(
    "paladin",
    "pilgrims-vow",
    "Pilgrim's Vow",
    "block",
    1,
    5,
    "ally",
    [],
    [],
    "Give an ally {v} Block. Draw 2 cards. Exhaust.",
    { draw: 2, exhaust: true },
  ),
].map((c, i) => ({ ...c, discovery: i % 9 >= 3 }));
