import { EXTRA_CLASSES, EXTRA_CARDS, EXTRA_STARTERS } from "./class-expansion";
export type ClassId =
  | "fighter"
  | "rogue"
  | "cleric"
  | "wizard"
  | "barbarian"
  | "ranger"
  | "necromancer"
  | "paladin";
export type Effect =
  "strike" | "spell" | "heal" | "block" | "poison" | "cleave" | "step";
export interface CardDef {
  id: string;
  name: string;
  owner: ClassId;
  cost: number;
  value: number;
  effect: Effect;
  target: "enemy" | "ally" | "self" | "all";
  ranks: number[];
  reach: number[];
  text: string;
  flavor: string;
  exhaust: boolean;
  discovery?: boolean;
  draw?: number;
  selfBlock?: number;
  move?: number;
  weaken?: number;
  poisonAmount?: number;
  pierce?: boolean;
  partyBlock?: number;
  cleanse?: boolean;
  targetBlock?: number;
  optionalMove?: boolean;
}
export const CLASSES: Record<
  ClassId,
  { name: string; title: string; hp: number; color: string; paths: string[] }
> = {
  ...EXTRA_CLASSES,
  fighter: {
    name: "Aldric",
    title: "Fighter",
    hp: 52,
    color: "#c79765",
    paths: ["Vanguard", "Executioner", "Warden"],
  },
  rogue: {
    name: "Vesper",
    title: "Rogue",
    hp: 38,
    color: "#90b29a",
    paths: ["Assassin", "Venomblade", "Duelist"],
  },
  cleric: {
    name: "Sister Iona",
    title: "Cleric",
    hp: 40,
    color: "#ddd0a1",
    paths: ["Dawnkeeper", "Inquisitor", "Oracle"],
  },
  wizard: {
    name: "Elias",
    title: "Wizard",
    hp: 32,
    color: "#9facdb",
    paths: ["Pyromancer", "Arcanist", "Chronomancer"],
  },
};
const c = (
  id: string,
  name: string,
  owner: ClassId,
  cost: number,
  value: number,
  effect: Effect,
  target: CardDef["target"],
  ranks: number[],
  reach: number[],
  text: string,
  flavor: string,
  exhaust = false,
): CardDef => ({
  id,
  name,
  owner,
  cost,
  value,
  effect,
  target,
  ranks,
  reach,
  text,
  flavor,
  exhaust,
});
export const CARDS: Record<string, CardDef> = Object.fromEntries(
  [
    c(
      "iron-cut",
      "Iron Cut",
      "fighter",
      1,
      9,
      "strike",
      "enemy",
      [1, 2],
      [1, 2],
      "Deal {v} damage.",
      "Steel remembers its purpose.",
    ),
    c(
      "hold-fast",
      "Hold Fast",
      "fighter",
      1,
      12,
      "block",
      "self",
      [],
      [],
      "Gain {v} Block.",
      "Behind me.",
    ),
    c(
      "sunder",
      "Sunder",
      "fighter",
      2,
      18,
      "strike",
      "enemy",
      [1],
      [1, 2],
      "Deal {v} damage.",
      "Even iron has a breaking point.",
    ),
    c(
      "backstab",
      "Backstab",
      "rogue",
      1,
      12,
      "strike",
      "enemy",
      [1, 2],
      [1, 2],
      "Deal {v} damage.",
      "A kindness, almost.",
    ),
    c(
      "venom",
      "Venom Needle",
      "rogue",
      1,
      4,
      "poison",
      "enemy",
      [],
      [1, 2, 3, 4],
      "Deal {v} damage. Apply 3 Poison.",
      "A small wound. A long ending.",
    ),
    c(
      "backstep",
      "Backstep",
      "rogue",
      0,
      5,
      "step",
      "self",
      [],
      [],
      "Gain {v} Block. Move back one rank.",
      "Leave only a shadow.",
    ),
    c(
      "mend",
      "Mending Light",
      "cleric",
      1,
      8,
      "heal",
      "ally",
      [2, 3],
      [],
      "Restore {v} HP to an ally. Exhaust.",
      "Something holy still answers.",
      true,
    ),
    c(
      "ward",
      "Pale Ward",
      "cleric",
      1,
      7,
      "block",
      "ally",
      [],
      [],
      "Give an ally {v} Block.",
      "Let the darkness wait.",
    ),
    c(
      "smite",
      "Smite",
      "cleric",
      1,
      8,
      "spell",
      "enemy",
      [2, 3],
      [1, 2, 3],
      "Deal {v} damage.",
      "Faith has a sharper edge.",
    ),
    c(
      "ember",
      "Ember Lance",
      "wizard",
      1,
      10,
      "spell",
      "enemy",
      [],
      [1, 2, 3, 4],
      "Deal {v} damage.",
      "The dark recoils.",
    ),
    c(
      "nova",
      "Cinderstorm",
      "wizard",
      2,
      8,
      "cleave",
      "all",
      [3, 4],
      [],
      "Deal {v} damage to every enemy.",
      "Let there be a little light.",
    ),
    c(
      "aegis",
      "Shield",
      "wizard",
      0,
      7,
      "block",
      "self",
      [],
      [],
      "Gain {v} Block. Exhaust.",
      "Fragile things can still protect.",
      true,
    ),
  ].map((x) => [x.id, x]),
);
// Discoveries are expedition rewards, never part of the sixteen-card starter kit.
const discoveries: (CardDef & { art: string })[] = [
  {
    ...c(
      "shield-bash",
      "Shield Bash",
      "fighter",
      1,
      7,
      "strike",
      "enemy",
      [1, 2],
      [1, 2],
      "Deal {v} damage. Gain 5 Block.",
      "The wall strikes back.",
    ),
    selfBlock: 5,
    art: "hold-fast",
  },
  {
    ...c(
      "reaping-arc",
      "Reaping Arc",
      "fighter",
      2,
      9,
      "cleave",
      "all",
      [1, 2],
      [],
      "Deal {v} damage to every enemy.",
      "Make room for the living.",
    ),
    art: "sunder",
  },
  {
    ...c(
      "breakthrough",
      "Breakthrough",
      "fighter",
      1,
      10,
      "strike",
      "enemy",
      [2, 3, 4],
      [1, 2],
      "Deal {v} damage. Advance one rank.",
      "There is still a way through.",
    ),
    move: -1,
    art: "iron-cut",
  },
  {
    ...c(
      "bodyguard",
      "Bodyguard",
      "fighter",
      1,
      9,
      "block",
      "ally",
      [],
      [],
      "Give an ally {v} Block. Gain 4 Block.",
      "No one falls alone.",
    ),
    selfBlock: 4,
    art: "hold-fast",
  },
  {
    ...c(
      "rally",
      "Rallying Cry",
      "fighter",
      1,
      5,
      "block",
      "self",
      [],
      [],
      "Gain {v} Block. Draw 2 cards. Exhaust.",
      "On your feet.",
      true,
    ),
    draw: 2,
    art: "hold-fast",
  },
  {
    ...c(
      "headsman",
      "Headsman's Due",
      "fighter",
      2,
      22,
      "strike",
      "enemy",
      [1],
      [1],
      "Deal {v} damage, ignoring Block. Exhaust.",
      "The oath is paid in full.",
      true,
    ),
    pierce: true,
    art: "sunder",
  },
  {
    ...c(
      "quickdraw",
      "Quickdraw",
      "rogue",
      0,
      4,
      "strike",
      "enemy",
      [],
      [1, 2, 3, 4],
      "Deal {v} damage. Draw 1 card. Exhaust.",
      "Gone before the echo.",
      true,
    ),
    draw: 1,
    art: "venom",
  },
  {
    ...c(
      "smoke-screen",
      "Smoke Screen",
      "rogue",
      1,
      8,
      "step",
      "self",
      [],
      [],
      "Gain {v} Block. Retreat one rank. Draw 1 card.",
      "Let them hunt a shadow.",
    ),
    draw: 1,
    art: "backstep",
  },
  {
    ...c(
      "nightshade",
      "Nightshade",
      "rogue",
      1,
      2,
      "poison",
      "enemy",
      [2, 3, 4],
      [1, 2, 3, 4],
      "Deal {v} damage. Apply 6 Poison. Exhaust.",
      "The last breath takes its time.",
      true,
    ),
    poisonAmount: 6,
    art: "venom",
  },
  {
    ...c(
      "shadow-lunge",
      "Shadow Lunge",
      "rogue",
      1,
      13,
      "strike",
      "enemy",
      [3, 4],
      [2, 3, 4],
      "Deal {v} damage. Advance one rank.",
      "Every shadow is a doorway.",
    ),
    move: -1,
    art: "backstab",
  },
  {
    ...c(
      "feint",
      "Feint",
      "rogue",
      1,
      6,
      "strike",
      "enemy",
      [1, 2],
      [1, 2],
      "Deal {v} damage. Reduce its next attack by 5.",
      "Watch the wrong hand.",
    ),
    weaken: 5,
    art: "backstab",
  },
  {
    ...c(
      "heartseeker",
      "Heartseeker",
      "rogue",
      2,
      18,
      "strike",
      "enemy",
      [2, 3, 4],
      [3, 4],
      "Deal {v} damage, ignoring Block.",
      "Distance is no sanctuary.",
    ),
    pierce: true,
    art: "venom",
  },
  {
    ...c(
      "sanctuary",
      "Sanctuary",
      "cleric",
      1,
      7,
      "block",
      "self",
      [2, 3],
      [],
      "Gain {v} Block. Give every other ally 4 Block.",
      "Gather beneath the light.",
    ),
    partyBlock: 4,
    art: "ward",
  },
  {
    ...c(
      "absolution",
      "Absolution",
      "cleric",
      1,
      11,
      "heal",
      "ally",
      [],
      [],
      "Restore {v} HP. Cleanse Poison. Exhaust.",
      "You need carry it no further.",
      true,
    ),
    cleanse: true,
    art: "mend",
  },
  {
    ...c(
      "censure",
      "Censure",
      "cleric",
      1,
      7,
      "spell",
      "enemy",
      [2, 3],
      [1, 2, 3, 4],
      "Deal {v} damage. Reduce its next attack by 4.",
      "Be still.",
    ),
    weaken: 4,
    art: "smite",
  },
  {
    ...c(
      "vespers",
      "Vespers",
      "cleric",
      1,
      5,
      "block",
      "ally",
      [],
      [],
      "Give an ally {v} Block. Draw 2 cards. Exhaust.",
      "A bell for those still breathing.",
      true,
    ),
    draw: 2,
    art: "ward",
  },
  {
    ...c(
      "martyrs-shield",
      "Martyr's Shield",
      "cleric",
      2,
      17,
      "block",
      "ally",
      [2, 3],
      [],
      "Give an ally {v} Block. Cleanse Poison.",
      "A promise made solid.",
    ),
    cleanse: true,
    art: "ward",
  },
  {
    ...c(
      "judgement",
      "Judgement",
      "cleric",
      2,
      14,
      "spell",
      "enemy",
      [2, 3],
      [1, 2, 3, 4],
      "Deal {v} damage, ignoring Block. Gain 5 Block.",
      "The light does not forgive everything.",
    ),
    pierce: true,
    selfBlock: 5,
    art: "smite",
  },
  {
    ...c(
      "arcane-thread",
      "Arcane Thread",
      "wizard",
      1,
      7,
      "spell",
      "enemy",
      [],
      [1, 2, 3, 4],
      "Deal {v} damage. Draw 1 card.",
      "Follow the loose thread.",
    ),
    draw: 1,
    art: "ember",
  },
  {
    ...c(
      "frost-bind",
      "Frost Bind",
      "wizard",
      1,
      6,
      "spell",
      "enemy",
      [3, 4],
      [1, 2, 3, 4],
      "Deal {v} damage. Reduce its next attack by 6.",
      "Even malice can freeze.",
    ),
    weaken: 6,
    art: "aegis",
  },
  {
    ...c(
      "forbidden-page",
      "Forbidden Page",
      "wizard",
      0,
      3,
      "block",
      "self",
      [],
      [],
      "Gain {v} Block. Draw 2 cards. Exhaust.",
      "One more page cannot hurt.",
      true,
    ),
    draw: 2,
    art: "aegis",
  },
  {
    ...c(
      "prism-ward",
      "Prism Ward",
      "wizard",
      1,
      10,
      "block",
      "ally",
      [3, 4],
      [],
      "Give an ally {v} Block. Draw 1 card.",
      "A thousand fragile walls.",
    ),
    draw: 1,
    art: "aegis",
  },
  {
    ...c(
      "starfall",
      "Starfall",
      "wizard",
      3,
      19,
      "cleave",
      "all",
      [4],
      [],
      "Deal {v} damage to every enemy. Exhaust.",
      "Something overhead finally answers.",
      true,
    ),
    art: "nova",
  },
  {
    ...c(
      "soul-siphon",
      "Soul Siphon",
      "wizard",
      1,
      8,
      "spell",
      "enemy",
      [3, 4],
      [1, 2, 3, 4],
      "Deal {v} damage. Gain 6 Block.",
      "Nothing is wasted.",
    ),
    selfBlock: 6,
    art: "ember",
  },
];
for (const card of discoveries) CARDS[card.id] = { ...card, discovery: true };
for (const card of EXTRA_CARDS) CARDS[card.id] = card;
export const DISCOVERIES = [
  ...discoveries,
  ...EXTRA_CARDS.filter((c) => c.discovery),
].map((c) => c.id);

export const STARTER = [
  "iron-cut",
  "iron-cut",
  "hold-fast",
  "sunder",
  "backstab",
  "backstab",
  "venom",
  "backstep",
  "mend",
  "ward",
  "smite",
  "ward",
  "ember",
  "ember",
  "nova",
  "aegis",
];
export const CLASS_STARTERS: Record<ClassId, string[]> = {
  fighter: STARTER.filter((id) => CARDS[id].owner === "fighter"),
  rogue: STARTER.filter((id) => CARDS[id].owner === "rogue"),
  cleric: STARTER.filter((id) => CARDS[id].owner === "cleric"),
  wizard: STARTER.filter((id) => CARDS[id].owner === "wizard"),
  ...EXTRA_STARTERS,
};
export const GEAR = {
  blade: {
    name: "Tempered edge",
    cost: 30,
    description: "+2 attack damage",
    stat: "power",
    value: 2,
  },
  coat: {
    name: "Pilgrim’s mail",
    cost: 25,
    description: "+8 maximum HP",
    stat: "hp",
    value: 8,
  },
  charm: {
    name: "Candle charm",
    cost: 25,
    description: "+3 Block at combat start",
    stat: "block",
    value: 3,
  },
} as const;
export type GearId = keyof typeof GEAR;
export const PATH_BONUSES = [
  "+2 attack damage",
  "+5 maximum HP and +2 healing",
  "+3 Block each turn",
];
export const ENCOUNTERS = {
  sentries: {
    tier: "combat",
    tactics: "steady",
    name: "The Silent Procession",
    subtitle: "The Hollow Cathedral",
    enemies: [
      ["sentinel", "Hollow Sentry", 30, 7],
      ["occultist", "Bell Acolyte", 22, 6],
      ["wraith", "Veiled Mourner", 20, 5],
    ],
  },
  beasts: {
    tier: "combat",
    tactics: "hunt",
    name: "Teeth in the Dark",
    subtitle: "The Sunken Cloister",
    enemies: [
      ["beast", "Crypt Hound", 25, 8],
      ["goblin", "Grave Pilferer", 22, 6],
      ["beast", "Starved Hound", 25, 7],
    ],
  },
  elite: {
    tier: "elite",
    tactics: "steady",
    name: "Keepers of the Bell",
    subtitle: "The Reliquary",
    enemies: [
      ["sentinel", "Oathless Knight", 40, 10],
      ["occultist", "Censer Priest", 32, 8],
      ["wraith", "Pale Witness", 25, 7],
    ],
  },
  boss: {
    tier: "boss",
    tactics: "bell",
    name: "The Last Bellkeeper",
    subtitle: "Heart of the Hollow Cathedral",
    enemies: [
      ["sentinel", "The Last Bellkeeper", 100, 12],
      ["wraith", "Bound Echo", 24, 6],
    ],
  },
  choir: {
    tier: "combat",
    tactics: "chorus",
    name: "The Drowned Choir",
    subtitle: "Flooded Choir Stalls",
    enemies: [
      ["sentinel", "Choir Warden", 28, 6],
      ["wraith", "Drowned Cantor", 24, 6],
      ["occultist", "Hollow Singer", 24, 6],
    ],
  },
  scavengers: {
    tier: "combat",
    tactics: "hunt",
    name: "A Feast of Candles",
    subtitle: "The Bone Market",
    enemies: [
      ["goblin", "Candle Thief", 24, 6],
      ["beast", "Marrow Hound", 30, 8],
      ["goblin", "Grave Collector", 23, 6],
    ],
  },
  procession: {
    tier: "combat",
    tactics: "steady",
    name: "The Iron Funeral",
    subtitle: "The Sepulchral Walk",
    enemies: [
      ["sentinel", "Iron Pallbearer", 36, 8],
      ["sentinel", "Coffin Guard", 30, 7],
      ["wraith", "Last Mourner", 21, 6],
    ],
  },
  covenant: {
    tier: "elite",
    tactics: "chorus",
    name: "The Ashen Covenant",
    subtitle: "The Sealed Sacristy",
    enemies: [
      ["sentinel", "Ashbound Protector", 38, 9],
      ["occultist", "Covenant Speaker", 34, 9],
      ["wraith", "Oath Collector", 28, 7],
    ],
  },
  hunt: {
    tier: "elite",
    tactics: "hunt",
    name: "The Pale Hunt",
    subtitle: "The Broken Kennels",
    enemies: [
      ["beast", "Pale Alpha", 45, 10],
      ["beast", "Chainbreaker", 33, 9],
      ["goblin", "Huntmaster", 27, 7],
    ],
  },
  abbess: {
    tier: "boss",
    tactics: "chorus",
    name: "The Unhallowed Abbess",
    subtitle: "The Choir of Ash",
    enemies: [
      ["occultist", "The Unhallowed Abbess", 94, 11],
      ["sentinel", "Vowbound Shield", 32, 8],
      ["wraith", "Last Hymn", 24, 6],
    ],
  },
  devourer: {
    tier: "boss",
    tactics: "hunt",
    name: "The Candle Devourer",
    subtitle: "The Lightless Nave",
    enemies: [
      ["beast", "The Candle Devourer", 110, 13],
      ["goblin", "Wick Collector", 28, 7],
    ],
  },
} as const;
export type EncounterId = keyof typeof ENCOUNTERS;
